### ISSUE TITLE
some way to get smoothing in region borders in the in-place slice? 

### ISSUE THREAD

**Issue by nsteinme** [dbirman/NPTrajectoryPlanner#43]
Not sure of the best algorithm but it's looking pretty choppy in a lot of places, especially as soon as you rotate out of coronal: 

<img width="199" alt="image" src="https://user-images.githubusercontent.com/7590975/157295583-541c7861-c28d-45d2-85c9-730e68865c49.png">

Seems like there should be some way to compute some nice sharp lines to plot here instead.

**Comment by dbirman** [comment]
Implemented in v0.6 when using the GPU renderer option
