### ISSUE TITLE
shadows of probes are cute but distracting

### ISSUE THREAD

**Issue by nsteinme** [dbirman/NPTrajectoryPlanner#47]
Part of SC in the image below is dark colored because of a shadow cast by the anterior lateral probe. I think if it's possible to make the probes not cast shadows it would be good, because the image is pretty graphically complex already. 

<img width="330" alt="image" src="https://user-images.githubusercontent.com/7590975/157298352-b4466ee2-733c-4473-bc9a-ff978f57e993.png">

**Comment by dbirman** [comment]
Fixed in v0.6
